#!/usr/bin/env bash

set -eo pipefail
docker cp boba_chains.json $(docker container ls  | grep '/safe-config-service' | awk '{print $1}'):/tmp/boba_chains.json
./run manage loaddata /tmp/boba_chains.json